version: "3.2"

services:
  postgres:
    container_name: postgres
    image: teamdigitale/postgres
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
